version: 2.1

executors:
  x86_64:
    docker:
      - image: cimg/base:2020.01
  aarch64:
    machine: 
      image: ubuntu-2004:202101-01
    resource_class: arm.medium

orbs:
  rust: circleci/rust@1.6.0

jobs:
  test:
    parameters:
      arch:
        type: executor
    executor: << parameters.arch >>
    environment:
      PATH: "$HOME/.cargo/bin/:$PATH"
    steps:
      - checkout
      - run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none -y
          source $HOME/.cargo/env
          rustup toolchain install nightly --allow-downgrade --profile minimal --component clippy
      - rust/build:
          release: true
      - rust/clippy
      - rust/test

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              arch: [x86_64, aarch64]
