version: 2.1

executors:
  x86_64:
    docker:
      - image: cimg/base:2020.01
  aarch64:
    machine: 
      image: arm-default
    resource_class: arm.medium

orbs:
  rust: circleci/rust@1.6.0

jobs:
  test:
    parameters:
      arch:
        type: executor
    executor: << parameters.arch >>
    steps:
      - checkout
      - run: curl -s https://static.rust-lang.org/rustup.sh | sh -s -- --channel=nightly
      - rust/build:
          release: true
      - rust/clippy
      - rust/test

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              arch: [x86_64, aarch64]
